### ISSUE TITLE
documentation structure

### ISSUE THREAD

**Issue by amgando** [nearprotocol/docs#105]
**Is your feature request related to a problem? Please describe.**
the current structure (the outline / table of contents) of our documentation isn't intuitive and doesn't seem to follow the typical flow

**Describe the solution you'd like**
by comparing several options we can pick / generate a better structure and reorganize the docs to match it

**Additional context**
here are a few examples of well structured docs
- https://codaprotocol.com/docs/
- https://wiki.polkadot.network/docs/en/
- https://docs.solana.com/book/

thoughts? @AnaisUrlichs and @potatodepaulo

**Comment by amgando** [comment]
specifically:
- the overall structure and prioritization of getting to success quickly
- developer intro is called out specifically
- protocol architecture is explained via video to begin with
- lots of warning and info callouts ( red warnings / blue notes ) help make it clear where docs are under construction or devs are likely to stump their toes

**Comment by ilblackdragon** [comment]
So I think I want to make sure we understand that we have 4 different users of this documentation, and we need to make it clear for people to self select into this groups and have clear navigation for them:
 - Core Contributor - must know how to compile / setup stuff, run it, debug it, contribute code etc. Ideally in future - find videos with walkthroughts the code and our updates. An external person should be able to productive to build a feature in nearcore / wallet / etc.
 - Integration Developer - uses nearlib / etc to build wallets / exchange integration / explorer / oracle etc. Doesn't really builds smart contract, but instead uses chain from outside. @vgrichina and @frol are operating in this capacity and can give feedback.
 - App Developer - builds smart contract, wants to setup node, UI with nearlib, etc. We can ask our Beta Program folk to give us feedback what's missing / what navigation they want.
 - Validator - setup node, stake, near-shell, how to create account, etc.

**Comment by ilblackdragon** [comment]
Btw, just UX thing - the fact that clicking on top level menu items doesn't really open anything is a bit annoying. Because after clicking I still need to make a choice between some other options while not getting any more information about what is this section really is about.

**Comment by frol** [comment]
@ilblackdragon I would extract the core contributor documentation into a completely separate one (rust doc should be a much better place to start with), though we should definitely have a link to it from the current documentation.

**Comment by amgando** [comment]
here's an [example](https://warrior.js.org/docs/en/player/overview) of a group using Docusaurus that has some relevant features: 

- clear set of top level nav entry points for different roles, `Player`, `Maker` and `Community` where the left hand nav changes to support the role.  _this is handled by adding new [top level nodes](https://github.com/olistic/warriorjs/blob/master/website/sidebars.json)  to `sidebars.json` and navigation links [defined](https://github.com/olistic/warriorjs/blob/master/website/siteConfig.js#L22-L29) in `siteConfig.js`_
- the first level of the sidebar is a small set (1 - 5 items) that's always open which makes it easy to scan
- contributing to the docs repo is just a link to GitHub at the top right
- multiple language support (although not sure if we need this at this point, maybe English and Chinese?)

what's missing here that we could use (soonish?) is [versioning](https://docusaurus.io/docs/en/versioning)

**Comment by amgando** [comment]
here's [another example](https://www.type-route.org/docs/api-reference/route-definition-builder/define-route) with accessible API docs:

- always open sidebar for quick scanning, 3 top-level items (intro, guides and api)
- intro includes quickstart and the "why?" followed by a list of stepwise guides _and call to action_ for missing docs _("Guide Missing? Still not sure how to do something? Ask a question on the GitHub repository.")_
- sidebar nav citing key abstractions `subcategories` in Docusaurus language (ie. *<Router>*, *<RouteDefinition>* )
- friendly method doc structure: 
  - signature
  - preamble / summary
  - parameters (each with a doc line)
  - example(s)

**Comment by amgando** [comment]
@ilblackdragon re: 
> _Btw, just UX thing - the fact that clicking on top level menu items doesn't really open anything is a bit annoying._

i think the built-in solution is to keep the nav open so it's scannable and doesn't collapse

**Comment by amgando** [comment]
@frol re: 
> _I would extract the core contributor documentation into a completely separate one_

i expect multiple top level entry points, each with their own sidebar nav will resolve this since it will feel like a different set of docs

**Comment by amgando** [comment]
closing since it's being handled by #136
