### ISSUE TITLE
[DOC] Usage examples for nearlib

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#106]
**Is your feature request related to a problem? Please describe.**
The goal is to make it easy for people to integrate into wallets / backend applications.

Current nearlib README (https://github.com/nearprotocol/nearlib) doesn't contain any examples of usage or links to such examples.

Same true about docs: we have "FRONTEND API (NEARLIB)" with a huge list of API items, but nothing how to use it.

**Describe the solution you'd like**
For this, we need a page with details how to use `nearlib` to create key pairs, create transactions, sign a transaction and send it to the network.

**Additional context**
Examples:
 - Intro README.md which describes high level ideas and shows how to sign & submit a tx https://github.com/EOSIO/eosjs#sending-a-transaction
 - Step by step guide to do different things with js library - https://github.com/meet-one/eosjs-guide
 - Usage section here https://github.com/cosmos/cosmos-sdk-js#usage

**Comment by amgando** [comment]
closing since it is being handled by other PRs #131 and  #136
