### ISSUE TITLE
[DOC] Needs to provide backup&recovery instruction for seed phrase

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/docs#108]
https://docs.nearprotocol.com/docs/local-setup/create-account#backup-private-key-manually describes how to backup keys manually from browser local storage.

However the recovery for such keys isn't supported. We should instead suggest to setup backup&recovery using seed phrase.

**Comment by AnaisUrlichs** [comment]
Changed it here https://github.com/nearprotocol/docs/pull/109

**Comment by amgando** [comment]
@AnaisUrlichs closing based on your merged PR
