### ISSUE TITLE
[DOC] Add minimal version of node for near-shell

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#119]
**Is your feature request related to a problem? Please describe.**
People have older version of node and our tools don't work. Errors are also not clear.

**Describe the solution you'd like**
Have version of node required (at least 12) on all the pages that mention near-shell

**Comment by amgando** [comment]
since we control NEAR Shell let's just handle the requirement there and keep docs free of exceptions

discussion here: https://github.com/nearprotocol/near-shell/issues/186
