### ISSUE TITLE
[BUG] Nearlib documentation issues

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/docs#132]
While @k06a was working on the bridge he has reported the following issues with nearlib documentation:
* Nearlib documentation is not googlable. Google search leads the following not useful links: https://docs.nearprotocol.com/docs/nearlib/ https://docs.nearprotocol.com/docs/overview/who-is-this-for.html ; Actually useful nearlib documentation is not found in Google: https://docs.nearprotocol.com/docs/development/examples/nearlib/introduction
* As reported by @ilblackdragon @k06a and @nearmax the menu interface is not intuitive: https://www.dropbox.com/s/76k6ffivcixb07e/Screenshot%202019-11-29%2010.38.11.png?dl=0 The gray color usually denotes inactive link (in our case it is the currently selected section). `FRONTEND API (NEARLIB)` is not clickable.
* The source code of nearlib does not allow to understand the API of nearlib. We possible better comments;

@k06a Is there anything else we are missing?

**Comment by amgando** [comment]
these issues have been addressed by recent updates to the docs
