### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by icerove** [nearprotocol/docs#149]
**Describe the bug**
Briefly describe the issue you're experiencing.
the model.js is lack of the first code line to serialize the file 

**Expected behavior**
Describe what you were expecting to find.
add `//@nearfile`

**:pencil: Location**
https://docs.nearprotocol.com/docs/tutorials/how-to-write-contracts-that-talk-to-each-other

**Comment by amgando** [comment]
closed by #154
