### ISSUE TITLE
Place game tutorial quickstart broken

### ISSUE THREAD

**Issue by jason00111** [nearprotocol/docs#15]
After clicking on the Near Studio quickstart link at the beginning of the Place game tutorial, I am brought to Near Studio. When I click "run" I get the following error:

`[error]: Task build failed: Invalid code point 6695714`

**Comment by potatodepaulo** [comment]
Updated this tutorial with the appropriate dependencies: https://docs.nearprotocol.com/tutorials/multiplayergame
