### ISSUE TITLE
[BUG] Google search result url has been moved

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/docs#153]
**Describe the bug**
Some breaking changes in doc recently is fantastic, but have this annoying side effect, for example, search this in google:
![image](https://user-images.githubusercontent.com/13259400/72138486-c0dfba80-3341-11ea-8baa-adffa09ff832.png)

First search result, when open, shows `Not Found`

**Expected behavior**
Describe what you were expecting to find.

**Screenshots**
![image](https://user-images.githubusercontent.com/13259400/72138571-e8cf1e00-3341-11ea-90ce-2281dc010541.png)

**:pencil: Location**
https://docs.nearprotocol.com/docs/development/examples/nearlib/introduction

**Possible solution**
I only know of redirect such pages, maybe also possible to let google know these

**Comment by amgando** [comment]
in general, an attempt was made to preserve all links from previous structure.  this particular link was added during the doc refresh process.  my mistake. i just removed this link using this tool from Google 

https://www.google.com/webmasters/tools/removals

will close this issue

**Comment by amgando** [comment]
just FYI, the content at this broken URL was refactored into multiple pages starting here: https://docs.nearprotocol.com/docs/roles/developer/examples/nearlib/introduction

**Comment by ailisp** [comment]
Great! Also thanks for the info of the removal tool, I didn't know

**Comment by amgando** [comment]
also FYI I added the link to this tool in the contributing readme of this repo
