### ISSUE TITLE
[DOC] What is gas and its relation to NEAR tokens?

### ISSUE THREAD

**Issue by frol** [nearprotocol/docs#158]
**Is your feature request related to a problem? Please describe.**
Gas vs NEAR tokens is a common question for newcomers.

**Describe the solution you'd like**
Here is my take on explaining this (we need to review this info as my understanding might be incomplete, and I think we should avoid comparison with "money"):

> gas is a unified unit of the computational cost, e.g. to store 1 byte of information is 1 gas and doing a computation of 2+2 takes 3 gas, etc. Token, on the other hand, is similar to "money", which you use to buy anything, including gas, which you spend to do computations.
>
> Thus, accounts have their balance in NEAR tokens and gas is bought on the fly when a transaction gets processed.
>
> So here is what happens. Account has its balance in NEAR tokens and when a user wants to send a transaction, he/she decides how much gas at most he/she is willing to spend for the transaction (some transactions require an almost constant amount of gas, but FunctionCalls are hard to predict); once the transaction reaches the network, it automatically "buys" gas for the current price, and executes the transaction; once the transaction is done, the leftover gas is converted back to NEAR tokens and the account gets only "charged" for the used gas.
>
> There is a prepaid gas for a transaction, and it only gets prepaid on the spot, so there is no way to prepay it for an account or something like that.

**Comment by amgando** [comment]
the current mention of gas in our docs is incorrect and misleading on [this page](https://docs.nearprotocol.com/docs/roles/developer/examples/nearlib/introduction)

> **the cost of data storage and computation on the network is measured in units of gas which is a configurable bit of network economics but is usually vanishingly small**
> 
> It costs exactly 2 gas (at the time of this writing) to "compute the creation of a new account" on the network. Gas is measured in yoctoNEAR or yNEAR, which is 10^24 times smaller than NEAR. For a sense of scale, with just 2 of the 10 NEAR in your new account you could happily afford to create a new account for every grain of sand on the planet (actually estimates suggest about 10^21 grains of sand on earth so you could do this every day for 3 years, not just once) and still have some NEAR tokens left over for a rainy day. Gas is measured as very very very small fraction of NEAR tokens.

i'll update it to match your clearer explanation

**Comment by frol** [comment]
I vote for having this fundamental information about what gas is in an “overview” section describing various terms used in Near instead of having this info buried in nearlib documentation.

/cc @nearmax

**Comment by amgando** [comment]
how about in the same section as other "Key Concepts" like `Account` and `Transaction`?
https://docs.nearprotocol.com/docs/concepts/account

**Comment by amgando** [comment]
this has been mentioned on Discord recently

NEAR
> Gas is measured in its own unit and the cost is computed by multiplying the gas price at the block which contains the transaction

DEV
> Is there somewhere I can read more about that?  I'm assuming gas price is set to 1? Which is probably generating the confusion here since it looks like the balance before / after the transaction is the same amount as gas burned, but its actually two different units subtracting with a gas amount * 1 NEAR / 1 gas conversion or alike

NEAR
 > No minimum gas price is 5000 yocto NEAR for now

---

also there is some related confusion about prepaid gas from an end-user perspective -- how is this handled?

DEV
> Belatedly, thanks for the pointer to the github issue on gas. I'm still not too clear on how prepaid gas works. My sense from reading existing docs is that NEAR lets smart contract/app developers choose to pay the gas cost for a user to call contract functions. The docs at nearprotocol.com/developers say The NEAR Wallet lets your users authorize low-stakes transactions without multiple pop-ups or in many cases, without even holding tokens. As a developer, how do I let users interact with my contract without them needing to hold tokens? Thanks for ur patience!

**Comment by frol** [comment]
> how about in the same section as other "Key Concepts" like Account and Transaction?

Sounds good to me

**Comment by amgando** [comment]
closed by #195
