### ISSUE TITLE
Place game tutorial error

### ISSUE THREAD

**Issue by jason00111** [nearprotocol/docs#16]
I'm following along with the "place" game tutorial. When I get to the second paragraph of step 3 I'm instructed to run the tests. Doing so results in the following errors:

```
[info]: Task build is running...
ERROR TS2304: Cannot find name 'globalStorage'.

   globalStorage.setItem(coords, value);
   ~~~~~~~~~~~~~
 in main.ts(4,2)


ERROR TS2304: Cannot find name 'globalStorage'.

   return globalStorage.getItem(coords);
          ~~~~~~~~~~~~~
 in main.ts(8,9)


WARNING AS102: User-defined: "Calling 'memory.allocate' requires a memory manager to be present."

     WARNING("Calling 'memory.allocate' requires a memory manager to be present.");
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/memory.ts(42,4)


WARNING AS102: User-defined: "Calling 'memory.allocate' requires a memory manager to be present."

     WARNING("Calling 'memory.allocate' requires a memory manager to be present.");
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/memory.ts(42,4)


ERROR TS2304: Cannot find name 'globalStorage'.

       let cellEntry = globalStorage.getItem(near.str(row) + "," + near.str(col));
                       ~~~~~~~~~~~~~
 in main.ts(19,22)


ERROR AS200: Conversion from type 'i32' to 'String' requires an explicit cast.

       arrResult[i] = cellEntry;
                      ~~~~~~~~~
 in main.ts(20,21)


WARNING AS102: User-defined: "Calling 'memory.free' requires a memory manager to be present."

     WARNING("Calling 'memory.free' requires a memory manager to be present.");
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/memory.ts(48,4)


[error]: Task build failed: Compile error
```

**Comment by vgrichina** [comment]
We'll update tutorial, for now I recommend starting with version linked in https://builtwithnear.com/near-place/

**Comment by jason00111** [comment]
Hmmm. The Near Studio quickstart doesn't work there either.

@vgrichina Is builtwithnear open source so I can open an issue there?

**Comment by evgenykuzyakov** [comment]
@jason00111 I think you have to "Fork" it first. What's the error do you see?

**Comment by jason00111** [comment]
The tests give this error:
![image](https://user-images.githubusercontent.com/20765448/53769959-4da02900-3e92-11e9-8dd6-b975eaf33a56.png)

Run gives this error:
![image](https://user-images.githubusercontent.com/20765448/53770029-85a76c00-3e92-11e9-9b8d-ee1dc647a988.png)

After forking, the tests give the same error but the app does successfully run.

**Comment by evgenykuzyakov** [comment]
Oh. Seems, the test is broken (for builtwithnear app), since I didn't update the test when I modified the original app.
Here is the error I see:
<img width="601" alt="test error" src="https://user-images.githubusercontent.com/470453/53772773-8b09b400-3e9c-11e9-862d-2227a0012974.png">


As for the requirement to click "Fork" before you can run, it's a bug and we should fix it. I created an issue to address this:
https://github.com/nearprotocol/NEARStudio/issues/93

**Comment by jason00111** [comment]
@evgenykuzyakov If it's open source, I could attempt to update the test.

**Comment by vgrichina** [comment]
@jason00111 test is right in the fiddle in `test.js` file

**Comment by jason00111** [comment]
@vgrichina Maybe I'm missing something. Where is the repo which I can make a PR to?

**Comment by vgrichina** [comment]
@jason00111 ah, there is really no dedicated repo for it yet. 

Might make sense to add as a template in https://github.com/nearprotocol/NEARStudio/tree/master/templates

**Comment by potatodepaulo** [comment]
Hey, I updated the tutorial! Should work now. If you get the chance to go through it, lmk!

**Comment by potatodepaulo** [comment]
Closing for now. If you find this issue persists, I'll reopen.
