### ISSUE TITLE
[BUG] Confusing navigation for tutorials

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/docs#162]
Some pages don't have an entry in the left-hand menu, so finding this information is not straightforward (see screenshots)
<img width="1175" alt="Screen Shot 2020-01-17 at 4 01 17 PM" src="https://user-images.githubusercontent.com/1320689/72654251-998d7c80-3943-11ea-9355-5d7999ee8db2.png">
<img width="1175" alt="Screen Shot 2020-01-17 at 4 02 04 PM" src="https://user-images.githubusercontent.com/1320689/72654255-a01bf400-3943-11ea-8e64-3d0e42ec7121.png">

**Comment by amgando** [comment]
@janedegtiareva both of the screenshots you shared have entries on the left hand side so i'm confused by this.

**Comment by amgando** [comment]
addressed by 85790af
