### ISSUE TITLE
[BUG] Near shell Windows issues needed

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/docs#166]
**Describe the bug**
On Windows, if a user follows the instructions to download NodeJS, the `near login` command will not work, citing that it cannot find the config file.

**Expected behavior**
`near login` loads the config file as expected and the user is able to login following the link.

**Screenshots**
![discord-screenshot-warning](https://user-images.githubusercontent.com/1042667/72918161-09ac5180-3cfa-11ea-9920-fe70834cd6ca.png)

**:pencil: Location**
https://docs.nearprotocol.com/docs/development/near-clitool

I believe I can add to the documentation on this page, and I think the Windows Subsystem Linux will be needed at this time in order to run `near login` and probably other near-shell commands.
Also, I tried changing forward and backslashes and the solution is not that simple.

**Comment by amgando** [comment]
@mikedotexe let me know if you need support on this

**Comment by mikedotexe** [comment]
> @mikedotexe let me know if you need support on this

Thanks! I think once we feel good about the pull request and merge it, we'll be good!
Longer term support for Windows is not in the scope, but that PR will help Windows folks get to a working spot :)
https://github.com/nearprotocol/docs/pull/167
