### ISSUE TITLE
Link to example contract in NEAR Studio has issues

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/docs#172]
**Describe the bug**
This may be an issue with NEAR Studio ultimately, but since the documentation references it, I'd like to make an issue here. There's a link to our online IDE that has instructions to click Run, but that brings up a dialog saying the user doesn't have permission to run it. Clicking cancel on this dialog does nothing, clicking okay "forks" the project, but then tries to open a site similar to `https://app.near.ai/app/f9vmyh73w/` and the content says, "Not found."

**Expected behavior**
When you click the link in the docs for NEAR Studio, the user is able to run to program as expected and see "Hello World."

**Screenshots**
![Kapture 2020-01-23 at 7 02 23](https://user-images.githubusercontent.com/1042667/72996109-f3ac9880-3dae-11ea-8050-bf946f4e6338.gif)

**:pencil: Location**
https://docs.nearprotocol.com/docs/development/writing-smart-contracts
The link at the end of "Below is a fully functioning smart contract (see it running **here**):"

**Comment by amgando** [comment]
seems like a previous version of NEAR Studio was expecting the app entry point to be `main.html` and has now changed to `index.html`.  will update docs with a new app for this example.

**Comment by amgando** [comment]
this is addressed in #203
