### ISSUE TITLE
[BUG] Assembly script link is broken in https://docs.nearprotocol.com/docs/roles/developer/quickstart

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/docs#186]
**Describe the bug**
In the section

> Using AssemblyScript
>
>    AssemblyScript Smart Contracts: near-runtime-ts is a collection of helpers that make your SmartContracts look a lot like TypeScript while compiling to Wasm for execution.

"AssemblyScript Smart Contracts:" link is broken

**:pencil: Location**
https://docs.nearprotocol.com/docs/roles/developer/quickstart

**Comment by amgando** [comment]
it should point to: https://docs.nearprotocol.com/docs/development/writing-smart-contracts

**Comment by vgrichina** [comment]
Fixed in https://github.com/nearprotocol/docs/commit/2ea52c1ae49251c6c1f6728cc8abf3b658607b34
