### ISSUE TITLE
[DOC] Explain how to access the `storage` object

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/docs#187]
**Is your feature request related to a problem? Please describe.**
In the documentation on Assembly Script: https://docs.nearprotocol.com/docs/development/writing-smart-contracts we mention that all the interactions with the storage should happen via `storage` object, and link to the storage API docs:

> Like with web servers, function calls are stateless. Any state that you want to save to the blockchain needs to be explicitly saved by interacting with the **storage** object.
>
> This object provides an interface to the blockchain storage. It is a standard key-value store where keys are strings and the values can be multiple types including string, bytes, u64. Anything else needs to be first converted into these types.
>
> See the **storage docs** and collections for the full reference.

We need to explain how to actually import and access the storage object. A simple example would be great.

**Describe the solution you'd like**
Add a simple example of a smart contract that uses raw storage (as opposed to persistent collections) and shows how to import `storage` and how to interface with it.

**Comment by amgando** [comment]
would it be sufficient to link existing examples in the docs?  or do we need a snippet of code inline here?

all of the following examples use `storage`, although limited to `setString` / `getString` and `setBytes` / `getBytes`

- [NEAR Wallet Integration](https://docs.nearprotocol.com/docs/tutorials/near-studio/near-wallet-integration)
- [Implement an Oracle](https://docs.nearprotocol.com/docs/tutorials/zero-to-hero)
- [Testing Smart Contracts](https://docs.nearprotocol.com/docs/tutorials/test-your-smart-contracts)
