### ISSUE TITLE
[META] Edit on GitHub link on every page

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/docs#194]
Let's have "Edit on GitHub" link for every doc page, so that it's immediately clear how to make fixes to any given page.

As suggested by @amgando it should be possible to do by putting a React component to the footer that resolves the current doc page to GitHub edit URL.

That way neither internal nor internal contributors will get confused regarding how to make fixes.

**Comment by amgando** [comment]
found it built in: https://docusaurus.io/docs/en/site-config#editurl-string

added the change to PR #196
