### ISSUE TITLE
Alphanet docs have a weird autoreload

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/docs#26]
To reproduce, open: https://docs.nearprotocol.com/quick_start/expert
Observe that web page opens, and there is a section:
"Expert: Run Alphanet deploy on GCP"
Then page reloads by itself, and the section changes to:
"Expert: Connect to NEAR Testnet"

**Comment by nearmax** [comment]
Press reload in the browser repeatedly for a greater effect.

**Comment by nearmax** [comment]
https://www.dropbox.com/s/5qfnijq49hl8oyr/Weird_docs.mov?dl=0

**Comment by potatodepaulo** [comment]
Can you reproduce now?

**Comment by nearmax** [comment]
Cannot reproduce.
