### ISSUE TITLE
[BUG] `txStatus` documentation is wrong

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/docs#296]
In https://docs.nearprotocol.com/docs/roles/developer/examples/nearlib/examples, the section on `near.connection.provider.txstatus` says
```
This method returns a ChunkView, one of NEAR platform's primitives, which itself is made up of a ChunkHeaderView and a collection of SignedTransactionViews and a collection of ReceiptViews
```
which is obviously incorrect.

**Comment by amgando** [comment]
yep, not sure what happened there.  i must've gotten confused about something.  can't recall now.
