### ISSUE TITLE
High level NEARlib.js

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#3]
Describe in high level NEARlib.js + examples how to use it.

**Comment by potatodepaulo** [comment]
https://docs.nearprotocol.com/client-api/js  <-- probably needs gentler intro than just API docs. So I won't close this yet

(Going to need maintenance, but this specific issue is done)

**Comment by potatodepaulo** [comment]
Closing this for different task that not related to autogenerated document.
