### ISSUE TITLE
[BUG] Turn down validator documentation

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#316]
**Describe the bug**
How to run nodes is outdated and should be turned down with a link to github where we have up to date docs, until it's rewritten.

**Comment by jimmy3dita** [comment]
Just updated the guide to reflect the current situation. Please note that also during the previous Stake Wars the network was running on Tatooine and not Testnet, and the docs weren't considered actual.

Here the updated release: https://docs.nearprotocol.com/docs/validator/staking
Here the committed PR: https://github.com/nearprotocol/docs/commit/443d872a0062f0d9180cf37694251b17e19a62a2

**Comment by amgando** [comment]
so should we close this then @jimmy3dita?

**Comment by jimmy3dita** [comment]
Docs are now up to date, so we can safely keep them. It will need another update next week when we'll update the docs to reflect our MainNet plans
