### ISSUE TITLE
Collections need better documentation

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/docs#32]
Currently documentation for collections is auto-generated and hard to read. We need better documentation and more examples explaining how they work.

**Comment by vgrichina** [comment]
I think we also need to name them in a way which will prevent confusion. At least one of participants was seriously confused by two different `Map`'s which behave completely differently. I think it makes sense to name them `PersistentMap`, `PersistentVector`, etc

**Comment by potatodepaulo** [comment]
@vgrichina that makes a lot of sense. Especially if we ever intend to have utility collections with things like `map` and `reduce` functions that aren’t persistent.

**Comment by vgrichina** [comment]
> Especially if we ever intend to have utility collections with things like map and reduce functions that aren’t persistent.

there are developed and available as part of AssemblyScript's std (which mostly mirrors JS)

**Comment by amgando** [comment]
this page of the docs seems to address this issue
https://docs.nearprotocol.com/docs/roles/developer/contracts/assemblyscript#collections
