### ISSUE TITLE
Develop locally with near-shell step 1: missing npm install

### ISSUE THREAD

**Issue by jasperdg** [nearprotocol/docs#39]
Nothing big but after calling: 

```
near new_project [YOUR_PROJECT_DIR]
```

Running  ```cd ./[YOUR_PROJECT_DIR] && npm install``` is still required

EDIT: This is described in the README but would be good to add to docs too.

**Comment by potatodepaulo** [comment]
Can you tell me where you first read the `near new_project` command?  I can add the extra instructions there.

**Comment by ckshei** [comment]
https://github.com/nearprotocol/docs/blob/master/docs/quick-start/developing-locally.md is actually where I was going to update it @potatodepaulo

**Comment by vgrichina** [comment]
@jasperdg thanks for catching this! Always feel free to edit markdown file and submit a PR if you find something missing, might be quicker.

**Comment by potatodepaulo** [comment]
Updated here: https://docs.nearprotocol.com/quick-start/local-development
