### ISSUE TITLE
npm test with local node fails

### ISSUE THREAD

**Issue by jasperdg** [nearprotocol/docs#40]
I tried to run `npm test` in a freshly build new project (running locally), the test fails and throws the following error:

> [unknown contract]: Runtime error: Account alice.near tries to create new account with 1000000000000, but only has 0

**Comment by jasperdg** [comment]
Update: After restarting my node the initial test ran and returned expected result. Second test run the same error as described in the initial issue occurs.

**Comment by jasperdg** [comment]
After following all instructions from the README `npm test` still only works once. To keep testing you'd need to keep restarting your node.

**Comment by vgrichina** [comment]
@jasperdg we are currently in process migrating to new backend (i.e. nightshade). It's recommended to use shard test net for resting for now, i.e. something like `NODE_ENV=development npm test`
