### ISSUE TITLE
[BUG] Incorrect storage doc link

### ISSUE THREAD

**Issue by kimlisa** [nearprotocol/docs#49]
**Describe the bug**
On [Writing Contracts: State](https://docs.nearprotocol.com/working-smart-contracts/writing-contracts#state) section, there is a link for "the storage docs", but the link is routed to Writing Contracts page, the same page I was on before navigating away, but from top.

**Expected behavior**
I expected to go to a doc page about Storages. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43280172/62186605-ba253400-b31b-11e9-8914-4ecd1b167882.png)

**:pencil: Location**
[Writing Contracts: State](https://docs.nearprotocol.com/working-smart-contracts/writing-contracts#state)

**Comment by potatodepaulo** [comment]
Thanks for pointing this out. Fixed: https://github.com/nearprotocol/docs/commit/10a01973bba4a400013eeda6fc50d820256ee203
