### ISSUE TITLE
Protocol details layout

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#5]
Add a basic layout of documentation for protocol details.

**Comment by potatodepaulo** [comment]
More than this? https://docs.nearprotocol.com/details

**Comment by potatodepaulo** [comment]
> More than this? https://docs.nearprotocol.com/details

This link is deprecated. Protocol details will be updated when Nightshade goes live.

**Comment by potatodepaulo** [comment]
Adding protocol details back in using Nightshade paper.

**Comment by potatodepaulo** [comment]
fixed: https://github.com/nearprotocol/docs/commit/c2ca7d1359bda66efa7c68a54d2af524775d8ba4
