### ISSUE TITLE
[DOC] Specify minimal nodejs version in staking instructions 

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/docs#50]
https://docs.nearprotocol.com/running-a-node

This should go in this section You will also need Near Shell, which which will require nodejs/npm

**Comment by vgrichina** [comment]
Probably good idea also to set proper `engines` in all of the `package.json` files we have:
https://docs.npmjs.com/files/package.json#engines

**Comment by potatodepaulo** [comment]
Fixed here: 
https://docs.nearprotocol.com/docs/validator/staking#requirements
