### ISSUE TITLE
[BUG] Links in TypeScript Contracts are broken

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#51]
**Describe the bug**
On pages under https://docs.nearprotocol.com/api-documentation/runtime-ts links are going to github, and some of the pages on github are missing.
For example on https://docs.nearprotocol.com/api-documentation/runtime-ts/modules/utility-module-near click `random32`

**Comment by potatodepaulo** [comment]
Fix exists in docusaurus-migration. Will kill this when merged.

**Comment by potatodepaulo** [comment]
Fixed with merge https://github.com/nearprotocol/docs/pull/68 and added fix for autogenerated docs https://github.com/nearprotocol/docs/commit/13266027e53592b314a8352cd2883fe9ba9dffd3
