### ISSUE TITLE
[BUG]  Broken link

### ISSUE THREAD

**Issue by breck7** [nearprotocol/docs#52]
**Describe the bug**

I clicked Developers to get here:
https://nearprotocol.com/developers/

Then clicked "Explore":
https://studio.nearprotocol.com/debugger

**Expected behavior**
Not broken link.

**Screenshots**

Here's a good tool to automate testing for broken links:

npm install -g linkinator
npx linkinator -r https://nearprotocol.com/

Or output links to CSV:
npx linkinator -r -f csv https://nearprotocol.com/

**:pencil: Location**
https://nearprotocol.com/developers/

**Comment by potatodepaulo** [comment]
Fixed: https://nearprotocol.com/developers/

**Comment by breck7** [comment]
Verified, thanks!
