### ISSUE TITLE
API docs generation

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#6]
Generate API docs from NEARlib, PyNEAR and NEARCore and put them here.

**Comment by potatodepaulo** [comment]
This needs a little more detail:
[ ] Code snippets are automatically injected *somewhere* in markdown with comments
[ ] Those somewheres are piped *here* in their respective locations
[ ] That process runs on CI

**Comment by amgando** [comment]
on hold til things stabilize. seems like #202 and related fix are good enough for now
