### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#7]
Herd developers to write tutorials. Goal to have at least 3 meaningful tutorials with one clear super tutorial.

**Comment by potatodepaulo** [comment]
Note for future Peter: Close this once the [Oracle](https://docs.nearprotocol.com/tutorials/oracle) example is done. (Or a comparable one)

**Comment by potatodepaulo** [comment]
TODO: Add `hello_world` example to docs tutorial section.

**Comment by potatodepaulo** [comment]
Complete to letter of the law. Will need weekly maintenance and regular new tutorials.

**Comment by eriktrautman** [comment]
@potatodepaulo Being technically correct is the best kind of correct.
