### ISSUE TITLE
[BUG] _contract_.contractpromise.md has missing contract name in `.then` API examples

### ISSUE THREAD

**Issue by frol** [nearprotocol/docs#70]
**Describe the bug**
`docs/runtime-ts/classes/_contract_.contractpromise.md` (is it auto-generated?) features `.then()` usage with a wrong number of arguments (the first argument must be contract name).

```js
  let callbackPromise = promise.then(
     "_onItemAdded",
     requestArgs.encode(),
     2,  // Attaching 2 additional requests, in case we need to do another call
  );
```

The comment about the number `2` is completely misleading. It is a gas amount and it should be a much greater number, e.g. `100000`.

**Expected behavior**
The example should work out of the box.

```js
  let callbackPromise = promise.then(
     context.contractName,
     "_onItemAdded",
     requestArgs.encode().serialize(),
     100000
  );
```

**:pencil: Location**
https://docs.nearprotocol.com/docs/runtime-ts/classes/_contract_.contractpromise.html

BTW, the link from the navigation menu is broken (does not include `.html`)!

**Comment by AnaisUrlichs** [comment]
@frol fixed the example; what do you mean by the link from the navigation menu is broken?

**Comment by frol** [comment]
> what do you mean by the link from the navigation menu is broken?

Navigating via https://docs.nearprotocol.com/ to "ASSEMBLYSCRIPT RUNTIME (NEAR-RUNTIME-TS)" -> "ContractPromise" I get "Not found" page since the url is `https://docs.nearprotocol.com/docs/runtime-ts/classes/_contract_.contractpromise` while `https://docs.nearprotocol.com/docs/runtime-ts/classes/_contract_.contractpromise.html` works fine.

**Comment by potatodepaulo** [comment]
Just a quick update: There is a weird rendering issue with the actual docusaurus build step: It generates the files as folders with an index.html file inside and tries to serve that against the route. This works for all of the other subfolders except for "classes/" in the runtime section. Working on a fix.

**Comment by potatodepaulo** [comment]
https://github.com/nearprotocol/docs/commit/13266027e53592b314a8352cd2883fe9ba9dffd3

**Comment by frol** [comment]
I still see the old examples with all the same issues (zero or two gas, and missing contract name)

**Comment by potatodepaulo** [comment]
https://github.com/nearprotocol/docs/commit/f04ecd090bf1999b587fcee5dca499cb0d0d302f

Thanks! Heres the fix.
