### ISSUE TITLE
[BUG] Documentation for boardcast_tx_commit RPC

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#77]
**Describe the bug**
Currently it says "Send Transaction (In development)" https://docs.nearprotocol.com/docs/interaction/rpc#send-transaction-in-development which is not true as we actually using this RPC for most of nearlib.

**Expected behavior**
Title: Send Transaction (wait until done)

RPC:
```
http post http://127.0.0.1:3030/ jsonrpc=2.0 method=broadcast_tx_commit params:="[<base 58 of the SignedTransaction>]" id="dontcare"
```

Result:
```
{"jsonrpc":"2.0","result":{"status":"Completed","transactions":[{"hash":"GLTdMcUAVT5DB6YEWABcMgASFuPGFMCbQkC8TcvZdby3","result":{"logs":[],"receipts":["8YrftHfvmDA4EAwf6BZe3d5TQd51joJW3JHpoj4iAUBF"],"result":null,"status":"Completed"}},{"hash":"8YrftHfvmDA4EAwf6BZe3d5TQd51joJW3JHpoj4iAUBF","result":{"logs":[],"receipts":[],"result":"","status":"Completed"}}]},"id":133}
```

**Comment by potatodepaulo** [comment]
https://github.com/nearprotocol/docs/commit/7c9000fc6f1b61cf3813a34b60f32d53c0d007f8
