### ISSUE TITLE
[DOC] FAQ section

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/docs#80]
**Is your feature request related to a problem? Please describe.**

Many people are asking the same questions on Discord over and over. This is a waste of valuable time, especially when we've answered this Q somewhere else. 

**Describe the solution you'd like**

1) A FAQ section that clearly answers the most basic questions
    a) We need to compile these.
2) Links to S.O. in the docs and FAQ

**Comment by amgando** [comment]
all roles now have an FAQ
