### ISSUE TITLE
[BUG] undefined title in docs.nearprotocol.com

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/docs#84]
**Describe the bug**
Going to https://docs.nearprotocol.com/docs/overview/who-is-this-for.html
Title is "Who is this for? - undefined"

**Expected behavior**
No undefined. Or something meaningful

**Screenshots**
![image](https://user-images.githubusercontent.com/13259400/66078915-d3af4b80-e517-11e9-8665-d3b2c520f698.png)

**:pencil: Location**
https://docs.nearprotocol.com/docs/overview/who-is-this-for.html

**Comment by potatodepaulo** [comment]
fixed: https://github.com/nearprotocol/docs/commit/9187cb8c8f6de4485064558beca1a0dea0532583
