### ISSUE TITLE
[BUG] Zero to Hero tutorial is outdated

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/docs#87]
https://docs.nearprotocol.com/docs/tutorials/zero-to-hero#step-0-get-familiar-with-the-near-ide-the-basic-layout-of-a-near-project

e.g. it mentions `assembly/near.ts`, which isn't a thing for a while. Maybe something else is out of date, need to be tested.

**Comment by potatodepaulo** [comment]
Cleaned up here: https://github.com/nearprotocol/docs/pull/91

Needs one more change to be fully updated, but this cleanup makes it functional.
