### ISSUE TITLE
[BUG] Discord link at the bottom of homepage expired

### ISSUE THREAD

**Issue by jantlustak** [nearprotocol/docs#88]
https://nearprotocol.com
Imo, best is edit that link when creating a new one so it never expires. 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/4503361/66646170-b3714200-ec25-11e9-853e-8d9c5fd02a33.png">

**Comment by AnaisUrlichs** [comment]
Got updated, closing the issue
