### ISSUE TITLE
[BUG] Structure for validators doesn't make sense

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#93]
**Describe the bug & expected behaviour**
Currently there when I click "Become a validator" I expect to have a full materials from how to start node locally, on Google or whatever cloud, how to create account and how to stake.

Instead there are few links to other docs which doesn't seem like people see and follow.

Finding "Running a node" under "Local Setup" is unexpected.
"Running a node on Windows" goes before "Running a node" in the list is also strange.

In "Running a node" the section for Google cloud is at the end. May be worth separating it into separate section which then links to the running node https://docs.nearprotocol.com/docs/local-setup/running-testnet#running-official-testnet-node-with-docker section for actually how to start.

**Comment by AnaisUrlichs** [comment]
The reason why it leads you to the other sections is that the steps are exactly the same. Otherwise, we would have to copy-paste the same information in different sections, making each section longer.

I will change the side-bar to display a different order + change the names of the sidebar so that each section is easier to find.

**Comment by potatodepaulo** [comment]
Drop off rate from the first page is 16%. I don't think that putting it all in one page makes sense, but I do think we can fix the flow.

**Comment by AnaisUrlichs** [comment]
As far as we can solve it in the current docs, the explanation is a lot clearer now. This will have to be addressed in a complete docs makeover.

**Comment by amgando** [comment]
this is being addressed this week and next

**Comment by amgando** [comment]
will close this for now and we can re-open if needed
