### ISSUE TITLE
[BUG] Contribution guideline is hard to find

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/docs#94]
**Describe the bug**
Contribution guideline ideally should be at the most prominent place.
Right now it's under "Community" > "Contribution Guidelines" > "Nearcore"
Specifically, we need the section about development in staging (and that it's the active branch) be very visible to everyone.
But also I always use Operations section for my copy&paste

**Comment by potatodepaulo** [comment]
Where do you think it should go? Under "Blockchain Interactions"?

**Comment by vgrichina** [comment]
I think it is expected to have one on GitHub as well:
https://github.com/nearprotocol/nearcore/community

**Comment by amgando** [comment]
addressed by https://github.com/nearprotocol/docs/pull/238
